// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgOOdRFLrCaHlm70ATvXSLUX2TsK90A7E',
    appId: '1:912609106272:android:870e4f4d8a8502d076e605',
    messagingSenderId: '912609106272',
    projectId: 'furnly-app',
    storageBucket: 'furnly-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlshq2Un7G66n0sOJANxEIOmLoHEQxUB8',
    appId: '1:912609106272:ios:3c1572f57d821ee076e605',
    messagingSenderId: '912609106272',
    projectId: 'furnly-app',
    storageBucket: 'furnly-app.firebasestorage.app',
    iosBundleId: 'com.example.furnly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2IQMMEaDT43pctp_zyauzpGD6vDSV_lU',
    appId: '1:912609106272:web:ece29666770d109876e605',
    messagingSenderId: '912609106272',
    projectId: 'furnly-app',
    authDomain: 'furnly-app.firebaseapp.com',
    storageBucket: 'furnly-app.firebasestorage.app',
    measurementId: 'G-HMDCRYBHGC',
  );
}
